DeploymentStatusScreen As screen:
    OnVisible: |-
        =UpdateContext(
            {
                showDeployStatusDialog: true,
                showDeploymentStatusDialogOverlay: false
            }
        );
        ClearCollect(
            SolutionBuilds,
            CustomAzureDevOps.GetBuildDefinitions(
                drpAdoOrganizations.Selected.AccountName,
                drpAdoProjects.Selected.name,
                {
                    name: "deploy-*-" & SelectedSolutionToView.uniquename,
                    includeAllProperties: true
                }
            ).value
        );
        Clear(SelectedSolutionLatestBuildStatuses);
        ForAll(
            SolutionBuilds As build,
            Collect(
                SelectedSolutionLatestBuildStatuses,
                {
                    uniquename: SelectedSolutionToView.uniquename,
                    importSolutionStatus: CustomAzureDevOps.GetPipelineRuns(
                        drpAdoOrganizations.Selected.AccountName,
                        drpAdoProjects.Selected.name,
                        build.id
                    ).value
                }
            );
            
        )

    DeploymentStatusDialog As groupContainer:
        BorderColor: =BorderColorValue
        BorderThickness: =BorderThicknessValue
        DisplayMode: =DisplayMode.Edit
        Fill: =BorderColorValue
        Height: =1080
        Visible: =showDeployStatusDialog
        Width: =1920
        ZIndex: =1

        rctDeployStatusDialog As rectangle:
            BorderColor: =ColorFade(rctDeployStatusDialog.Fill, -20%)
            DisabledFill: =rctDeployStatusDialog.Fill
            Fill: =RGBA(255, 255, 255, 1)
            Height: =1080
            HoverFill: =ColorFade(rctDeployStatusDialog.Fill, 20%)
            PressedFill: =ColorFade(rctDeployStatusDialog.Fill, -20%)
            Width: =1920
            ZIndex: =1

        lblDeployStatusDialogTitle As label:
            Align: =Center
            Color: =RGBA(255, 255, 255, 1)
            Fill: =PrimaryColor2Value
            FontWeight: =Semibold
            Height: =64
            Size: =16
            Text: ="DEPLOYMENT STATUS (" & SelectedSolutionToView.friendlyname & ")"
            Width: =1920
            ZIndex: =6

        icoDeployStatusDialogClose As icon.Cancel:
            BorderColor: =ColorFade(icoDeployStatusDialogClose.Fill, -20%)
            Color: =RGBA(255, 255, 255, 1)
            DisabledFill: =ColorFade(icoDeployStatusDialogClose.Fill, -80%)
            Height: =55
            HoverBorderColor: =ColorFade(icoDeployStatusDialogClose.BorderColor, 20%)
            HoverColor: =ColorFade(icoDeployStatusDialogClose.Color, 20%)
            HoverFill: =ColorFade(icoDeployStatusDialogClose.Fill, 20%)
            Icon: =Icon.Cancel
            OnSelect: |-
                =Navigate(
                    ReturnScreen,
                    ScreenTransition.Fade
                );
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            PressedBorderColor: =ColorFade(icoDeployStatusDialogClose.BorderColor, -20%)
            PressedColor: =ColorFade(icoDeployStatusDialogClose.Color, -20%)
            PressedFill: =ColorFade(icoDeployStatusDialogClose.Fill, -20%)
            Visible: =!IsBlankOrError(ReturnScreen)
            Width: =55
            X: =1851
            Y: =4
            ZIndex: =7

        "Gallery1 As gallery.'BrowseLayout_Horizontal_TwoTextOneImageVariant_ver4.0'":
            Height: =1016
            Items: =SelectedSolutionLatestBuildStatuses
            TemplatePadding: =0
            TemplateSize: =280
            Width: =857
            X: =531
            Y: =64
            ZIndex: =8

            Image1 As image:
                BorderColor: =ColorFade(Image1.Fill, -20%)
                Height: =168
                HoverBorderColor: =ColorFade(Image1.BorderColor, 20%)
                HoverFill: =ColorFade(Image1.Fill, 20%)
                Image: |-
                    =Switch(
                        First(ThisItem.importSolutionStatus).result,
                        "active",
                        LookUp(
                            StageStatesIcons,
                            state = "notStarted"
                        ).image,
                        "succeeded",
                        LookUp(
                            StageStatesIcons,
                            state = "succeeded"
                        ).image,
                        "failed",
                        LookUp(
                            StageStatesIcons,
                            state = "failed"
                        ).image,
                        LookUp(
                            StageStatesIcons,
                            state = "empty"
                        ).image
                    )
                OnSelect: =Navigate(DeploymentHistoryScreen, Fade);
                PressedBorderColor: =ColorFade(Image1.BorderColor, -20%)
                PressedFill: =ColorFade(Image1.Fill, -20%)
                Width: =194
                X: =(Parent.TemplateWidth / 2) - (Self.Width / 2)
                Y: =141
                ZIndex: =1

            Title1 As label:
                Align: =Align.Center
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =First(ThisItem.importSolutionStatus).pipeline.name
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.TemplateWidth - 64
                X: =32
                Y: =Image1.Y + Image1.Height + 16
                ZIndex: =2

            Subtitle1 As label:
                Align: =Align.Center
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =First(ThisItem.importSolutionStatus).result
                VerticalAlign: =VerticalAlign.Top
                Width: =Title1.Width
                X: =Title1.X
                Y: =Title1.Y + Title1.Height + 8
                ZIndex: =3

    DeploymentStatusDialogOverlay As rectangle:
        BorderColor: =ColorFade(DeploymentStatusDialogOverlay.Fill, -20%)
        DisabledFill: =DeploymentStatusDialogOverlay.Fill
        Fill: =RGBA(0, 0, 0, .5)
        Height: =1080
        HoverFill: =RGBA(0, 0, 0, .5)
        PressedFill: =ColorFade(DeploymentStatusDialogOverlay.Fill, -20%)
        Visible: =showDeploymentStatusDialogOverlay
        Width: =1920
        ZIndex: =3

