DeploymentHistoryScreen As screen:
    OnVisible: |-
        =UpdateContext(
            {
                showDeployStatusDialog: true,
                showDeploymentStatusDialogOverlay: false
            }
        );
        ClearCollect(
            SolutionBuilds,
            CustomAzureDevOps.GetBuildDefinitions(
                drpAdoOrganizations.Selected.AccountName,
                drpAdoProjects.Selected.name,
                {
                    name: "deploy-*-" & SelectedSolutionToView.uniquename,
                    includeAllProperties: true
                }
            ).value
        );
        Clear(SelectedSolutionLatestBuildStatuses);
        ForAll(
            SolutionBuilds As build,
            Collect(
                SelectedSolutionLatestBuildStatuses,
                {
                    uniquename: SelectedSolutionToView.uniquename,
                    importSolutionStatus: CustomAzureDevOps.GetPipelineRuns(
                        drpAdoOrganizations.Selected.AccountName,
                        drpAdoProjects.Selected.name,
                        build.id
                    ).value
                }
            );
            
        )

    DeploymentHistoryDialog As groupContainer:
        BorderColor: =BorderColorValue
        BorderThickness: =BorderThicknessValue
        DisplayMode: =DisplayMode.Edit
        Fill: =BorderColorValue
        Height: =1080
        Visible: =showDeployStatusDialog
        Width: =1920
        ZIndex: =1

        rctDeployHistoryDialog As rectangle:
            BorderColor: =ColorFade(rctDeployHistoryDialog.Fill, -20%)
            DisabledFill: =rctDeployHistoryDialog.Fill
            Fill: =RGBA(255, 255, 255, 1)
            Height: =1080
            HoverFill: =ColorFade(rctDeployHistoryDialog.Fill, 20%)
            PressedFill: =ColorFade(rctDeployHistoryDialog.Fill, -20%)
            Width: =1920
            ZIndex: =1

        lblDeployHistoryDialogTitle As label:
            Align: =Center
            Color: =RGBA(255, 255, 255, 1)
            Fill: =PrimaryColor2Value
            FontWeight: =Semibold
            Height: =64
            Size: =16
            Text: ="DEPLOYMENT HISTORY (" & SelectedSolutionToView.friendlyname & ")"
            Width: =1920
            ZIndex: =6

        icoDeployHistoryDialogClose As icon.Cancel:
            BorderColor: =ColorFade(icoDeployHistoryDialogClose.Fill, -20%)
            Color: =RGBA(255, 255, 255, 1)
            DisabledFill: =ColorFade(icoDeployHistoryDialogClose.Fill, -80%)
            Height: =55
            HoverBorderColor: =ColorFade(icoDeployHistoryDialogClose.BorderColor, 20%)
            HoverColor: =ColorFade(icoDeployHistoryDialogClose.Color, 20%)
            HoverFill: =ColorFade(icoDeployHistoryDialogClose.Fill, 20%)
            Icon: =Icon.Cancel
            OnSelect: |-
                =Navigate(
                    DeploymentStatusScreen,
                    ScreenTransition.Fade
                );
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            PressedBorderColor: =ColorFade(icoDeployHistoryDialogClose.BorderColor, -20%)
            PressedColor: =ColorFade(icoDeployHistoryDialogClose.Color, -20%)
            PressedFill: =ColorFade(icoDeployHistoryDialogClose.Fill, -20%)
            Visible: =!IsBlankOrError(ReturnScreen)
            Width: =55
            X: =1851
            Y: =4
            ZIndex: =7

        "Gallery2 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver4.0'":
            Height: =1016
            Items: =First(SelectedSolutionLatestBuildStatuses).importSolutionStatus
            Layout: =Layout.Vertical
            TemplatePadding: =0
            TemplateSize: =Min(160, Self.Height - 60)
            Width: =1920
            Y: =64
            ZIndex: =8

            Image3 As image:
                BorderColor: =ColorFade(Image3.Fill, -20%)
                Height: =128
                HoverBorderColor: =ColorFade(Image3.BorderColor, 20%)
                HoverFill: =ColorFade(Image3.Fill, 20%)
                Image: |-
                    =Switch(
                        ThisItem.result,
                        "active",
                        LookUp(
                            StageStatesIcons,
                            state = "notStarted"
                        ).image,
                        "succeeded",
                        LookUp(
                            StageStatesIcons,
                            state = "succeeded"
                        ).image,
                        "failed",
                        LookUp(
                            StageStatesIcons,
                            state = "failed"
                        ).image,
                        LookUp(
                            StageStatesIcons,
                            state = "empty"
                        ).image
                    )
                OnSelect: =Select(Parent)
                PressedBorderColor: =ColorFade(Image3.BorderColor, -20%)
                PressedFill: =ColorFade(Image3.Fill, -20%)
                Width: =128
                X: =16
                Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                ZIndex: =1

            Title3 As label:
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =ThisItem.createdDate
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.TemplateWidth - Image3.Width - 104
                X: =Image3.X + Image3.Width + 24
                Y: =44
                ZIndex: =2

            Subtitle2 As label:
                Height: =Self.Size * 1.8
                OnSelect: =
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =
                VerticalAlign: =VerticalAlign.Top
                Width: =Title3.Width
                X: =Title3.X
                Y: =Title3.Y + Title3.Height + 4
                ZIndex: =3

            NextArrow1 As icon.ChevronRight:
                AccessibleLabel: =Self.Tooltip
                BorderColor: =ColorFade(NextArrow1.Fill, -20%)
                DisabledFill: =ColorFade(NextArrow1.Fill, -80%)
                Height: =60
                HoverBorderColor: =ColorFade(NextArrow1.BorderColor, 20%)
                HoverColor: =ColorFade(NextArrow1.Color, 20%)
                HoverFill: =ColorFade(NextArrow1.Fill, 20%)
                Icon: =Icon.ChevronRight
                OnSelect: =Select(Parent)
                PaddingBottom: =10
                PaddingLeft: =10
                PaddingRight: =10
                PaddingTop: =10
                PressedBorderColor: =ColorFade(NextArrow1.BorderColor, -20%)
                PressedColor: =ColorFade(NextArrow1.Color, -20%)
                PressedFill: =ColorFade(NextArrow1.Fill, -20%)
                TabIndex: =0
                Tooltip: ="View item details"
                Width: =60
                X: =Parent.TemplateWidth - Self.Width - 5
                Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                ZIndex: =4

            Separator4 As rectangle:
                BorderColor: =ColorFade(Separator4.Fill, -20%)
                DisabledFill: =Separator4.Fill
                Height: =1
                HoverFill: =ColorFade(Separator4.Fill, 20%)
                OnSelect: =Select(Parent)
                PressedFill: =ColorFade(Separator4.Fill, -20%)
                Width: =Parent.TemplateWidth
                Y: =Parent.TemplateHeight - 1
                ZIndex: =5

    DeploymentHistoryDialogOverlay As rectangle:
        BorderColor: =ColorFade(DeploymentHistoryDialogOverlay.Fill, -20%)
        DisabledFill: =DeploymentHistoryDialogOverlay.Fill
        Fill: =RGBA(0, 0, 0, .5)
        Height: =1080
        HoverFill: =RGBA(0, 0, 0, .5)
        PressedFill: =ColorFade(DeploymentHistoryDialogOverlay.Fill, -20%)
        Visible: =showDeploymentStatusDialogOverlay
        Width: =1920
        ZIndex: =3

